import { Card } from "@/components/ui/card";

export default function DataSources() {
  const dataSources = [
    {
      name: "Industrial Sensor Dataset",
      type: "Real-time sensor data",
      status: "Available",
      statusColor: "bg-green-500/20 text-green-400 border-green-500/30",
      description: "Live telemetry from industrial motor sensors",
    },
    {
      name: "Simulation Engine",
      type: "Synthetic fault scenarios",
      status: "Active",
      statusColor: "bg-blue-500/20 text-blue-400 border-blue-500/30",
      description: "Digital twin simulation for testing and demo",
    },
    {
      name: "IoT Gateway",
      type: "Edge computing",
      status: "Not connected",
      statusColor: "bg-gray-500/20 text-gray-400 border-gray-500/30",
      description: "Ready for edge device integration",
    },
    {
      name: "Live Industrial Asset",
      type: "Production equipment",
      status: "Not connected",
      statusColor: "bg-gray-500/20 text-gray-400 border-gray-500/30",
      description: "Connect to real equipment for production monitoring",
    },
  ];

  return (
    <div className="p-6 space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-foreground mb-2">Data Sources</h2>
        <p className="text-muted-foreground">
          Connected data sources and integration status.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {dataSources.map((source, idx) => (
          <Card key={idx} className={`border p-6 ${source.statusColor}`}>
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-bold text-lg">{source.name}</h3>
                <p className="text-sm opacity-75">{source.type}</p>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-semibold bg-black/30">
                {source.status}
              </span>
            </div>
            <p className="text-sm opacity-75">{source.description}</p>
          </Card>
        ))}
      </div>

      <Card className="bg-card border-border p-6">
        <h3 className="text-lg font-bold text-foreground mb-4">Current Mode</h3>
        <p className="text-foreground mb-2">
          The application is currently running in <span className="font-semibold">Demo Simulation Mode</span>.
        </p>
        <p className="text-sm text-muted-foreground">
          All sensor data is generated by the simulation engine. To connect real data sources, configure the API endpoints
          in the Settings page.
        </p>
      </Card>

      <Card className="bg-blue-500/10 border border-blue-500/30 p-4">
        <p className="text-sm text-blue-300">
          <span className="font-semibold">Production Integration:</span> To connect real data sources, implement the data
          source adapters in the backend and update the service layer to fetch from your IoT gateway or industrial asset.
        </p>
      </Card>
    </div>
  );
}
